Daniel's Toys
=============

toys is a small collection of environmental utilities. Basically
its a library of files I use to become "comfortable" in front
of a Unix or Linux machine. Each utility shares the characteristic
that it is too small to be interesting on its own.

It is neither organised nor intended to be consumed verbatim.

Instead you should either ignore it and go and read something
more interesting or you should use it as inspiration. Treat it
as a collection of ideas to be plundered rather than as a
functional work.

Organisation
------------

* Files in the top-level directory mirror similarly named
  files located in a typical Unix-like home directory.
* bashrc.d/ contains fragments to be included from a .bashrc file.
* bin/ contains executable scripts.
* clang_complete/ is a git sub-module containing the VIM support for
  clang based autocompletion (git submodule init; git submodule update;
  cd clang_complete/; make && make install)
* clang-format/ contains clang format descriptions of some common
  coding styles. It also contains clang-format.py (from LLVM distro)
  that must be placed into ~/.vim/bin.

